export const PERMISSIONS = {
  LIST_EMPLOYEES: 'LIST_EMPLOYEES',
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES',
  APPROVE_EMPLOYEES: 'APPROVE_EMPLOYEES',
  MANAGE_EXITS: 'MANAGE_EXITS',
  APPROVE_EXITS: 'APPROVE_EXITS',
  LIST_LOANS: 'LIST_LOANS',
  MANAGE_LOANS: 'MANAGE_LOANS',
  APPROVE_LOANS: 'APPROVE_LOANS',
  MANAGE_ONBOARDING: 'MANAGE_ONBOARDING',
  LIST_PAYROLLS: 'LIST_PAYROLLS',
  MANAGE_PAYROLLS: 'MANAGE_PAYROLLS',
  APPROVE_PAYROLL_OVERRIDE: 'APPROVE_PAYROLL_OVERRIDE',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
  APPROVE_DOCUMENT_DELETION: 'APPROVE_DOCUMENT_DELETION',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
