export const PERMISSIONS = [
  'LIST_EMPLOYEES',
  'MANAGE_EMPLOYEES',
  'APPROVE_EMPLOYEES',
  'MANAGE_EXITS',
  'APPROVE_EXITS',
  'LIST_LOANS',
  'MANAGE_LOANS',
  'APPROVE_LOANS',
  'MANAGE_RECRUITMENT',
  'APPROVE_RECRUITMENT',
  'MANAGE_ONBOARDING',
  'LIST_PAYROLLS',
  'MANAGE_PAYROLLS',
  'APPROVE_PAYROLL_OVERRIDE',
  'MANAGE_USERS',
  'MANAGE_DOCUMENTS',
  'APPROVE_DOCUMENT_DELETION',
  'APPROVE_JOB_POSTINGS',
  'MANAGE_JOB_POSTINGS',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
